# Generated by Django 4.0.5 on 2022-07-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('bodyStyle', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('rentCharge', models.PositiveIntegerField()),
                ('inventory', models.PositiveBigIntegerField()),
            ],
        ),
    ]
