# Generated by Django 4.0.6 on 2022-08-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Vehicle Make')),
                ('mod', models.CharField(max_length=50, verbose_name='Vehicle Model')),
                ('year', models.CharField(max_length=50, verbose_name='Vehicle Year')),
                ('mile', models.CharField(default='', max_length=50, verbose_name='Vehicle mile')),
                ('trans', models.CharField(default='', max_length=50, verbose_name='Vehicle trans')),
                ('body', models.CharField(default='', max_length=50, verbose_name='Vehicle type')),
                ('color', models.CharField(default='', max_length=50, verbose_name='Vehicle color')),
                ('price', models.CharField(default=0, max_length=50, verbose_name='Vehicle Price')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('interiorImage', models.ImageField(default='images/default.png', upload_to='images/')),
                ('secondaryImage', models.ImageField(default='images/default.png', upload_to='images/')),
                ('slug', models.SlugField(default=0, max_length=255)),
                ('licensePlate', models.CharField(max_length=8)),
                ('current_inventory', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ManyToManyField(to='car.vehicle')),
            ],
        ),
    ]
