# Generated by Django 4.0.6 on 2022-07-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Vehicle Make')),
                ('mod', models.CharField(max_length=50, verbose_name='Vehicle Model')),
                ('year', models.CharField(max_length=50, verbose_name='Vehicle Year')),
                ('price', models.CharField(default=0, max_length=50, verbose_name='Vehicle Price')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('slug', models.SlugField(default=0, max_length=255)),
            ],
        ),
    ]
