# Generated by Django 4.0.6 on 2022-07-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle Year'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle Year'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mile',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle Make'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='trans',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle Model'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
