# Generated by Django 4.0.6 on 2022-07-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_vehicle_body_vehicle_color_vehicle_mile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='interiorImage',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='secondaryImage',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle body'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mile',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle mile'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='trans',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle trans'),
        ),
    ]
