# Generated by Django 4.0.6 on 2022-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_vehicle_interiorimage_vehicle_secondaryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body',
            field=models.CharField(default='', max_length=50, verbose_name='Vehicle type'),
        ),
    ]
