# Generated by Django 4.0.6 on 2022-08-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_vehicle_price_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
