# Generated by Django 4.0.6 on 2022-08-06 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0007_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='renter',
            field=models.ManyToManyField(blank='True', null='True', to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
    ]
