# Generated by Django 4.0.6 on 2022-08-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_remove_vehicle_renter_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.vehicle'),
        ),
    ]
