# Generated by Django 4.0.6 on 2022-08-07 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_remove_reservation_vehicle_reservation_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
