# Generated by Django 4.0.6 on 2022-08-07 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
