# Generated by Django 4.0.5 on 2022-07-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.CharField(default=0, max_length=50, verbose_name='Vehicle Price'),
        ),
    ]
