# Generated by Django 4.0.5 on 2022-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
