# Generated by Django 4.0.5 on 2022-07-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
        ),
    ]
